# see https://github.com/sigoden/aichat/blob/main/config.example.yaml

keybindings: vi

compress_threshold: 30000

model: openrouter:deepseek/deepseek-v4-flash:nitro
clients:
  - type: openai-compatible
    name: openrouter
    api_base: https://openrouter.ai/api/v1
